In [ ]:
!pip install -U datasets huggingface_hub fsspec

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-4.8.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.7.1)
Collecting huggingface_hub
  Downloading huggingface_hub-1.7.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (2025.3.0)
Collecting fsspec
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)
Downloading datasets-4.8.3-py3-none-any.whl (526 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.8/526.8 kB 10.4 MB/s eta 0:00:00
Downloading huggingface_hub-1.7.2-py3-none-any.whl (618 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 618.0/618.0 kB 23.7 MB/s eta 0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.5/202.5 kB 15.6 MB/s eta 0:00:00
Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 23.8 MB/s eta 0:00:00
Installing collected packages: pyarrow, fsspec, huggingface_hub, datasets
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 1.7.1
    Uninstalling huggingface_hub-1.7.1:
      Successfully uninstalled huggingface_hub-1.7.1

In [1]:
!pip install -U bitsandbytes>=0.46.1

In [2]:
!pip install trl peft

Collecting trl
  Downloading trl-0.29.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.13.0)
Requirement already satisfied: datasets>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from trl) (4.0.0)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.0)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.7.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.7.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.4.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.24.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl) (2025.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.25.0->peft) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.25.0->peft) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.25.0->peft) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.25.0->peft) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (0.1.2)
Downloading trl-0.29.1-py3-none-any.whl (530 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.0/531.0 kB 15.0 MB/s eta 0:00:00
Installing collected packages: trl
Successfully installed trl-0.29.1

In [3]:
import os

from google.colab import userdata
os.environ['HF_TOKEN']=userdata.get('HF_TOKEN')

In [4]:
from datasets import Dataset, load_dataset

ds = load_dataset("newfacade/LeetCodeDataset")
ds

README.md:   0%|          | 0.00/665 [00:00<?, ?B/s]

LeetCodeDataset-train.jsonl:   0%|          | 0.00/93.6M [00:00<?, ?B/s]

LeetCodeDataset-test.jsonl: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/2641 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/228 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['task_id', 'question_id', 'difficulty', 'tags', 'problem_description', 'starter_code', 'estimated_date', 'prompt', 'completion', 'entry_point', 'test', 'input_output', 'query', 'response'],
        num_rows: 2641
    })
    test: Dataset({
        features: ['task_id', 'question_id', 'difficulty', 'tags', 'problem_description', 'starter_code', 'estimated_date', 'prompt', 'completion', 'entry_point', 'test', 'input_output', 'query', 'response'],
        num_rows: 228
    })
})

In [5]:
sample = ds['train'].select(range(20)).to_pandas()
sample.head(2)

,task_id,question_id,difficulty,tags,problem_description,starter_code,estimated_date,prompt,completion,entry_point,test,input_output,query,response
0,two-sum,1,Easy,"[Array, Hash Table]",Given an array of integers nums and an integer...,"class Solution:\n def twoSum(self, nums: Li...",2015-08-07,import random\nimport functools\nimport collec...,"class Solution:\n def twoSum(self, nums: Li...",Solution().twoSum,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums = [3,3], target = 6', 'output...",You are an expert Python programmer. You will ...,"To solve this problem efficiently, we can use ..."
1,add-two-numbers,2,Medium,"[Recursion, Linked List, Math]",You are given two non-empty linked lists repre...,# Definition for singly-linked list.\n# class ...,2015-08-07,import heapq\nimport itertools\nfrom sortedcon...,# Definition for singly-linked list.\n# class ...,Solution().addTwoNumbers,def check(candidate):\n assert is_same_list...,"[{'input': 'l1 = [9,8,7], l2 = [1,2,3]', 'outp...",You are an expert Python programmer. You will ...,```python\n# Definition for singly-linked list...

In [ ]:
print(''.join(sample['completion'][0]))

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        d = {}
        for i, x in enumerate(nums):
            if (y := target - x) in d:
                return [d[y], i]
            d[x] = i

In [ ]:
print(''.join(sample['response'][0]))

To solve this problem efficiently, we can use a hash map (dictionary in Python) to store the numbers we have seen so far and their indices. This allows us to check in constant time whether the complement of the current number (i.e., `target - current_number`) has already been encountered. This approach reduces the time complexity from O(n^2) to O(n).

Here's the implementation:

```python
from typing import List

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        # Create a dictionary to store the numbers and their indices
        num_to_index = {}

        # Iterate over the list of numbers
        for index, num in enumerate(nums):
            # Calculate the complement
            complement = target - num

            # Check if the complement is already in the dictionary
            if complement in num_to_index:
                # If found, return the indices of the complement and the current number
                return [num_to_index[complement], index]

            # Otherwise, add the current number and its index to the dictionary
            num_to_index[num] = index
```

### Explanation:
1. We initialize an empty dictionary `num_to_index` to store numbers and their indices as we iterate through the list.
2. For each number in the list, we calculate its complement with respect to the target.
3. We check if this complement is already in the dictionary:
   - If it is, we have found the two numbers that add up to the target, and we return their indices.
   - If it is not, we add the current number and its index to the dictionary.
4. This approach ensures that we only pass through the list once, achieving a time complexity of O(n).

In [6]:
cols = ds['train'].column_names
columns_needed_to_dropped=[]
for col in cols:
    if col=='problem_description' or col=='response':
        print(type(col))
        continue
    else:
        columns_needed_to_dropped.append(col)
columns_needed_to_dropped

<class 'str'>
<class 'str'>

['task_id',
 'question_id',
 'difficulty',
 'tags',
 'starter_code',
 'estimated_date',
 'prompt',
 'completion',
 'entry_point',
 'test',
 'input_output',
 'query']

In [7]:
ds = ds.remove_columns(columns_needed_to_dropped)
ds

DatasetDict({
    train: Dataset({
        features: ['problem_description', 'response'],
        num_rows: 2641
    })
    test: Dataset({
        features: ['problem_description', 'response'],
        num_rows: 228
    })
})

In [8]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model, TaskType
from trl import SFTTrainer, SFTConfig
import torch

In [10]:
model_id = 'deepseek-ai/deepseek-coder-1.3b-base'

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code = True)

config.json:   0%|          | 0.00/631 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/793 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

In [11]:
print(tokenizer.chat_template)

print(hasattr(tokenizer, "chat_template"))

None
True

In [12]:
CHAT_TEMPLATE = """{%- for message in messages %}
    {%- if message['role'] == 'user' %}
        {{- '<|user|>\n' + message['content'] + '\n' }}
    {%- elif message['role'] == 'assistant' %}
        {{- '<|assistant|>\n' + message['content'] + eos_token }}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|assistant|>\n' }}
{%- endif %}
"""
print(''.join(CHAT_TEMPLATE))

{%- for message in messages %}
    {%- if message['role'] == 'user' %}
        {{- '<|user|>
' + message['content'] + '
' }}
    {%- elif message['role'] == 'assistant' %}
        {{- '<|assistant|>
' + message['content'] + eos_token }}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|assistant|>
' }}
{%- endif %}

In [13]:
tokenizer.chat_template = CHAT_TEMPLATE
print(tokenizer.chat_template)

{%- for message in messages %}
    {%- if message['role'] == 'user' %}
        {{- '<|user|>
' + message['content'] + '
' }}
    {%- elif message['role'] == 'assistant' %}
        {{- '<|assistant|>
' + message['content'] + eos_token }}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|assistant|>
' }}
{%- endif %}

In [15]:
problem_description = ds['train']['problem_description'][0]
problem_response = ds['train']['response'][0]

#checking the Chat Template:
messages=[
    { 'role': 'user', 'content': problem_description },
    {"role":"assistant", "content":problem_response}
]

prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
print(prompt)

<|user|>
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice.
You can return the answer in any order.

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]

Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]


Constraints:

2 <= nums.length <= 104
-109 <= nums[i] <= 109
-109 <= target <= 109
Only one valid answer exists.


Follow-up: Can you come up with an algorithm that is less than O(n2) time complexity?
<|assistant|>
To solve this problem efficiently, we can use a hash map (dictionary in Python) to store the numbers we have seen so far and their indices. This allows us to check in constant time whether the complement of the current number (i.e., `target - current_number`) has already been encountered. This approach reduces the time complexity from O(n^2) to O(n).

Here's the implementation:

```python
from typing import List

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        # Create a dictionary to store the numbers and their indices
        num_to_index = {}

        # Iterate over the list of numbers
        for index, num in enumerate(nums):
            # Calculate the complement
            complement = target - num

            # Check if the complement is already in the dictionary
            if complement in num_to_index:
                # If found, return the indices of the complement and the current number
                return [num_to_index[complement], index]

            # Otherwise, add the current number and its index to the dictionary
            num_to_index[num] = index
```

### Explanation:
1. We initialize an empty dictionary `num_to_index` to store numbers and their indices as we iterate through the list.
2. For each number in the list, we calculate its complement with respect to the target.
3. We check if this complement is already in the dictionary:
   - If it is, we have found the two numbers that add up to the target, and we return their indices.
   - If it is not, we add the current number and its index to the dictionary.
4. This approach ensures that we only pass through the list once, achieving a time complexity of O(n).<｜end▁of▁sentence｜>

In [16]:
#Setting the pad-token:
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.eos_token_id

In [18]:
def format_to_chat_template(example):


  messages = [
      {
          "role":"user",
          "content":example['problem_description'].strip()
      },
      {
          "role":"assistant",
          "content":example['response'].strip()
      }
  ]

  example['text'] = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)

  return example

formatted_ds = ds.map(format_to_chat_template)

In [19]:
print(''.join(formatted_ds['train']['text'][0]))

<|user|>
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice.
You can return the answer in any order.

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]

Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]


Constraints:

2 <= nums.length <= 104
-109 <= nums[i] <= 109
-109 <= target <= 109
Only one valid answer exists.


Follow-up: Can you come up with an algorithm that is less than O(n2) time complexity?
<|assistant|>
To solve this problem efficiently, we can use a hash map (dictionary in Python) to store the numbers we have seen so far and their indices. This allows us to check in constant time whether the complement of the current number (i.e., `target - current_number`) has already been encountered. This approach reduces the time complexity from O(n^2) to O(n).

Here's the implementation:

```python
from typing import List

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        # Create a dictionary to store the numbers and their indices
        num_to_index = {}

        # Iterate over the list of numbers
        for index, num in enumerate(nums):
            # Calculate the complement
            complement = target - num

            # Check if the complement is already in the dictionary
            if complement in num_to_index:
                # If found, return the indices of the complement and the current number
                return [num_to_index[complement], index]

            # Otherwise, add the current number and its index to the dictionary
            num_to_index[num] = index
```

### Explanation:
1. We initialize an empty dictionary `num_to_index` to store numbers and their indices as we iterate through the list.
2. For each number in the list, we calculate its complement with respect to the target.
3. We check if this complement is already in the dictionary:
   - If it is, we have found the two numbers that add up to the target, and we return their indices.
   - If it is not, we add the current number and its index to the dictionary.
4. This approach ensures that we only pass through the list once, achieving a time complexity of O(n).<｜end▁of▁sentence｜>

In [22]:
eval_dataset

Dataset({
    features: ['problem_description', 'response', 'text'],
    num_rows: 228
})

In [23]:
train_dataset = formatted_ds['train'].select(range(1000))
eval_dataset = formatted_ds['test'].select(range(150))

In [24]:
train_dataset = train_dataset.remove_columns(['problem_description', 'response'])
eval_dataset = eval_dataset.remove_columns(['problem_description', 'response'])
print(train_dataset)
print(eval_dataset)

Dataset({
    features: ['text'],
    num_rows: 1000
})
Dataset({
    features: ['text'],
    num_rows: 150
})

In [ ]:
sample = ds['train'].select(range(20)).map(format_to_chat_template)
sample

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

Dataset({
    features: ['problem_description', 'response', 'text'],
    num_rows: 20
})

In [ ]:
print(''.join(sample['text'][0]))

<|user|>
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice.
You can return the answer in any order.

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].

Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]

Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]


Constraints:

2 <= nums.length <= 104
-109 <= nums[i] <= 109
-109 <= target <= 109
Only one valid answer exists.


Follow-up: Can you come up with an algorithm that is less than O(n2) time complexity?
<|assistant|>
To solve this problem efficiently, we can use a hash map (dictionary in Python) to store the numbers we have seen so far and their indices. This allows us to check in constant time whether the complement of the current number (i.e., `target - current_number`) has already been encountered. This approach reduces the time complexity from O(n^2) to O(n).

Here's the implementation:

```python
from typing import List

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        # Create a dictionary to store the numbers and their indices
        num_to_index = {}

        # Iterate over the list of numbers
        for index, num in enumerate(nums):
            # Calculate the complement
            complement = target - num

            # Check if the complement is already in the dictionary
            if complement in num_to_index:
                # If found, return the indices of the complement and the current number
                return [num_to_index[complement], index]

            # Otherwise, add the current number and its index to the dictionary
            num_to_index[num] = index
```

### Explanation:
1. We initialize an empty dictionary `num_to_index` to store numbers and their indices as we iterate through the list.
2. For each number in the list, we calculate its complement with respect to the target.
3. We check if this complement is already in the dictionary:
   - If it is, we have found the two numbers that add up to the target, and we return their indices.
   - If it is not, we add the current number and its index to the dictionary.
4. This approach ensures that we only pass through the list once, achieving a time complexity of O(n).<｜end▁of▁sentence｜>

In [ ]:
sample_map = sample.to_pandas()
sample_map.head(2)

,problem_description,response,text
0,Given an array of integers nums and an integer...,"To solve this problem efficiently, we can use ...",<|user|>\nGiven an array of integers nums and ...
1,You are given two non-empty linked lists repre...,```python\n# Definition for singly-linked list...,<|user|>\nYou are given two non-empty linked l...

In [25]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit = True,
    bnb_4bit_use_double_quant = True,
    bnb_4bit_quant_type = "nf4",
    bnb_4bit_compute_dtype = torch.bfloat16
)


model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config = bnb_config,
    trust_remote_code = True,
    device_map = "auto"
)

pytorch_model.bin:   0%|          | 0.00/2.69G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.69G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/119 [00:00<?, ?B/s]

In [26]:
# Required before adding LoRA to a quantized model
model = prepare_model_for_kbit_training(model)

model.config.use_cache = False         # disable KV cache during training
model.config.pretraining_tp = 1

In [27]:
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    inference_mode=False,
)

model = get_peft_model(model, lora_config)

# How many params are actually being trained?
model.print_trainable_parameters()
# → trainable params: ~5M  ||  all params: ~1.3B  ||  trainable%: ~0.4%

trainable params: 14,991,360 || all params: 1,361,463,296 || trainable%: 1.1011

In [28]:
# Calculate total training steps first
total_steps = (len(train_dataset) // (2 * 4)) * 3
# formula: (dataset_size // (batch_size * grad_accum)) * epochs

warmup_steps = int(0.05 * total_steps)  # 5% of total steps as integer
print(f"Total steps: {total_steps}, Warmup steps: {warmup_steps}")

Total steps: 375, Warmup steps: 18

In [29]:
# ── 7. Training Arguments ──────────────────────────────────────────────────────
sft_config = SFTConfig(
    output_dir="./deepseek-leetcode-qlora",

    # Training loop
    num_train_epochs=2,
    per_device_train_batch_size=2,        # keep low for 1.3B on T4/L4
    gradient_accumulation_steps=4,        # effective batch = 2 * 4 = 8

    # Optimizer
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_steps=18,
    weight_decay=0.01,
    optim="paged_adamw_8bit",            # memory-efficient optimizer from bitsandbytes

    # Precision
    #fp16=True,
   bf16=True,                           # use bf16 if your GPU supports it (A100/L4)

    # Sequence
    max_length=1024,                 # LeetCode problems + solutions fit in 1024
    dataset_text_field="text",           # column name in our formatted dataset

    # Logging & Saving
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none",                    # change to "wandb" if you use W&B
    disable_tqdm=False
)

In [30]:
from tqdm.notebook import tqdm
from tqdm.auto import tqdm


trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    args=sft_config,
    processing_class=tokenizer,
)

# ── 9. Train! ──────────────────────────────────────────────────────────────────
trainer.train()

Adding EOS to train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1000 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/150 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/150 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/150 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 32014}.

TrainOutput(global_step=250, training_loss=0.32405397987365725, metrics={'train_runtime': 8582.0865, 'train_samples_per_second': 0.233, 'train_steps_per_second': 0.029, 'total_flos': 1.2357025468121088e+16, 'train_loss': 0.32405397987365725})

In [46]:
from huggingface_hub import login
login()

In [37]:
model_id

'deepseek-ai/deepseek-coder-1.3b-base'

In [39]:
from transformers import AutoModelForCausalLM
from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained(model_id)

model = PeftModel.from_pretrained(base_model, "/content/deepseek-leetcode-qlora/checkpoint-250")

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

In [41]:
model = model.merge_and_unload()

In [44]:
model.save_pretrained("deepseek-leetcode-qlora-merged")
tokenizer.save_pretrained("deepseek-leetcode-qlora-merged")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('deepseek-leetcode-qlora-merged/tokenizer_config.json',
 'deepseek-leetcode-qlora-merged/chat_template.jinja',
 'deepseek-leetcode-qlora-merged/tokenizer.json')

In [47]:
model.push_to_hub("gajasankarraja/leetcode-deepseek-merged-1.3b")
tokenizer.push_to_hub("gajasankarraja/leetcode-deepseek-merged-1.3b")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...g65mlby/model.safetensors:   0%|          | 11.0kB / 2.69GB

README.md: 0.00B [00:00, ?B/s]

CommitInfo(commit_url='https://huggingface.co/gajasankarraja/leetcode-deepseek-merged-1.3b/commit/05cbc7e9252003d5bf4d603885f2457d56548923', commit_message='Upload tokenizer', commit_description='', oid='05cbc7e9252003d5bf4d603885f2457d56548923', pr_url=None, repo_url=RepoUrl('https://huggingface.co/gajasankarraja/leetcode-deepseek-merged-1.3b', endpoint='https://huggingface.co', repo_type='model', repo_id='gajasankarraja/leetcode-deepseek-merged-1.3b'), pr_revision=None, pr_num=None)